In [2]:
import numpy as np


In [3]:
X=np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]]
)
Y=np.array([
    [0],
    [1],
    [1],
    [0],
])

In [ ]:
class Neural:
    def __init__(self):
        np.random.seed(42)
        #Weights of layer 1

        # random.rand fills the matrix with random floats between 0.0 and 1.0
        #  The shape of input X= (4,2) 
        # in forward pass we have Z1= np.dot(X,self.W1)+bias
        # so weight is (4,2).(2,6)=(4,6) so bias should be (1,6) as it should add to every weight
        self.W1=np.random.randn(2,6)
        print(self.W1)
        # i have (4,6) here so in order to get  single output i need w2 to be in (6,1) shape so we get(4,1)
        self.W2=np.random.randn(6,1)
        print(self.W2)#(no of hidden layers,output or in case their is next layer that hidden layers)
        # why bias in 1,number of neurons ?? bcoz numpy performs broadcasting 
        # [b1,b2,b3,b4,b5,b6] this will be the bias of the 6 neurons 
        # when we add the dot product with the bias numpy see this and does broadcasting 
        # [b1,b2,b3,b4,b5,b6]
        # [b1,b2,b3,b4,b5,b6]........
        # it goes on and matches the shape of dot product so we add the correct bias to the correct neuron

        # why zeros bcoz we initialise the bias to 0
        # why (( ))(2 brackets) it represents a matrix (2d array)
        self.b1= np.zeros((1,6))

        # why (1,1) bcoz we already got (4,1) this is the output so we need (1,1) so numpy adds this same bias to every row 
        self.b2=np.zeros((1,1))
    def sigmoid(self,x):
        return 1/(1+np.exp(-x))
    # f'(x) = f(x) * (1 - f(x))
    def sigmoid_der(self,x):
        return x*(1-x)
    
    def forward_prop(self,X):
        self.Z1=np.dot(X,self.W1)+self.b1
        self.A1=self.sigmoid(self.Z1)

        self.Z2=np.dot(self.A1,self.W2)+self.b2
        self.A2=self.sigmoid(self.Z2)

        return self.A2
    def backward_prop(self,X,Y,output,learning_rate=0.1):
        # in output layer 
        error=Y-output # shape of error is (4,1)
        
        # sigmoid is always in the shape of the error
        # Without sensitivity, the network wouldn't know which neurons are capable of learning and which ones are stuck if they are confident then weight update will be low 
        # if the sensitivity is low means it's prediction is not confident so we get lower value bcoz of sigmoid so we update the weights even more 
        # sensitivity = Error * derivative 
        # Weight update= Input signal * sensitivity 
        sensitivity=error*self.sigmoid_der(output)
        # 2. Hidden Layer  
        # hidden layer is of the shape (4,6) 
        hidden_layer_error = np.dot(sensitivity, self.W2.T)

        # shape(4,6)
        hidden_sensitivity = hidden_layer_error * self.sigmoid_der(self.A1)
        

        # 3. Updates (Use np.dot to combine inputs and errors)
        self.W2 += np.dot(self.A1.T, sensitivity) * learning_rate
        self.W1 += np.dot(X.T, hidden_sensitivity) * learning_rate
        
        # 4. Bias Updates (Sum the errors across the batch)

        # axis = 0 collapes all the rows to one row 
        # shape of sensitivity(1,1)
        # shape of hidden_sensitivity(1,6)
        self.b2 += np.sum(sensitivity, axis=0, keepdims=True) * learning_rate
        self.b1 += np.sum(hidden_sensitivity, axis=0, keepdims=True) * learning_rate
        

nn=Neural()

for epoch in range(30000):
    output=nn.forward_prop(X)
    nn.backward_prop(X,Y,output)
    if epoch % 1000 == 0:
        loss = np.mean(np.square(Y - output))
        print(f"Epoch {epoch} - Loss: {loss:.4f}")

print("\nFinal Predictions:")
print(nn.forward_prop(X))
        
# if we get  final predictions like nan then it is explosing gradient problem where weights are too high and gradient is too far from minima 

[[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439  0.54256004 -0.46341769 -0.46572975]]
[[ 0.24196227]
 [-1.91328024]
 [-1.72491783]
 [-0.56228753]
 [-1.01283112]
 [ 0.31424733]]
Epoch 0 - Loss: 0.4308
Epoch 1000 - Loss: 0.1954
Epoch 2000 - Loss: 0.0623
Epoch 3000 - Loss: 0.0186
Epoch 4000 - Loss: 0.0090
Epoch 5000 - Loss: 0.0056
Epoch 6000 - Loss: 0.0039
Epoch 7000 - Loss: 0.0030
Epoch 8000 - Loss: 0.0024
Epoch 9000 - Loss: 0.0020
Epoch 10000 - Loss: 0.0017
Epoch 11000 - Loss: 0.0014
Epoch 12000 - Loss: 0.0013
Epoch 13000 - Loss: 0.0011
Epoch 14000 - Loss: 0.0010
Epoch 15000 - Loss: 0.0009
Epoch 16000 - Loss: 0.0008
Epoch 17000 - Loss: 0.0008
Epoch 18000 - Loss: 0.0007
Epoch 19000 - Loss: 0.0007
Epoch 20000 - Loss: 0.0006
Epoch 21000 - Loss: 0.0006
Epoch 22000 - Loss: 0.0005
Epoch 23000 - Loss: 0.0005
Epoch 24000 - Loss: 0.0005
Epoch 25000 - Loss: 0.0005
Epoch 26000 - Loss: 0.0004
Epoch 27000 - Loss: 0.0004
Epoch 28000 - L

In [ ]:
# why randn is used instead of rand ? 
# bcoz randn assigns positive and negative weights so it get a lower positive or weakly confident prediction which through back propagation we will get adjust the weights 
# if we use rand we will get all positive weights so the initial neurons all move to same direction in positive direction so sigmoid output is almost equal to 1 so we get lower weight change so the predictions will be stuck at 50 percent
